apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-abwktlop
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-abwktlop:68c73a27f5af192c40fe8f0b854d5d179ea8a831@sha256:bf04cd3b7fe779cf4453a6887a8aa46b25c377ae92da197ed051e5749ef32f3f
          name: container-image
